apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: kaniko-deployment 
spec: 
  selector: 
    matchLabels: 
      app: kaniko 
  replicas: 3  # tells deployment to run 2 pods matching the template 
  template: 
    metadata: 
      labels: 
        app: kaniko 
    spec: 
      containers: 
      - name: kaniko 
        image: ashaik65/myweb:2
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: kaniko-service 
spec: 
  selector: 
    app: kaniko 
  ports: 
  - protocol: TCP 
    port: 80 
    targetPort: 80 
    nodePort: 32000 
  type: NodePort 
